const OUTLOOK_BADGE = {
  'Contender':                    'badge-green',
  'Contender (needs production)': 'badge-green',
  'Window Contender':             'badge-orange',
  'Reload':                       'badge-blue',
  'Reload (sell vets for youth)': 'badge-blue',
  'Rebuild':                      'badge-red',
  'Rebuild (future value)':       'badge-red',
}

function rankColor(rank) {
  if (rank === 1)  return '#d69e2e'
  if (rank <= 3)   return '#38a169'
  if (rank >= 9)   return '#e53e3e'
  if (rank >= 7)   return '#dd6b20'
  return 'var(--text-secondary)'
}

function formatGeneratedAt(ts) {
  if (!ts) return null
  try {
    return new Date(ts).toLocaleDateString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
    })
  } catch {
    return null
  }
}

export default function PowerRankings({ data }) {
  const rankings    = (data?.powerRankings?.rankings || []).slice().sort((a, b) => a.rank - b.rank)
  const generatedAt = formatGeneratedAt(data?.powerRankings?.generated_at)

  return (
    <div className='page'>
      <div className='page-title'>Power Rankings</div>
      <div className='page-subtitle'>
        AI-generated dynasty power rankings
        {generatedAt ? ` · Last updated ${generatedAt}` : ' · Not yet generated'}
      </div>

      {rankings.length === 0 ? (
        <div className='card' style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)', fontSize: '14px' }}>
          Power rankings haven't been generated yet. Run the <code>power_rankings</code> notebook or trigger the GitHub Actions workflow.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {rankings.map(team => {
            const badgeClass = OUTLOOK_BADGE[team.outlook] || 'badge-blue'
            const color      = rankColor(team.rank)

            return (
              <div key={team.rank} className='card' style={{ padding: '16px 20px' }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
                  <div style={{
                    fontSize: '28px', fontWeight: 800, color,
                    minWidth: '44px', lineHeight: 1.1, paddingTop: '3px', textAlign: 'center',
                  }}>
                    #{team.rank}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap', marginBottom: '6px' }}>
                      <span style={{ fontSize: '16px', fontWeight: 700, color: 'var(--text-primary)' }}>
                        {team.team_name}
                      </span>
                      {team.team_name !== team.owner && (
                        <span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>
                          ({team.owner})
                        </span>
                      )}
                      <span className={`badge ${badgeClass}`}>{team.outlook}</span>
                    </div>
                    <div style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.65 }}>
                      {team.blurb}
                    </div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      <div style={{ marginTop: '1.25rem', fontSize: '11px', color: 'var(--text-muted)', textAlign: 'center' }}>
        Rankings generated by Claude AI every Tuesday based on current dynasty values, outlook classifications, and roster composition. For entertainment purposes.
      </div>
    </div>
  )
}
