import { useLeague } from '../contexts/LeagueContext'

const WMH_ID   = '1312130103358021632'
const WMH_NAME = "Wilson's Moms House"

export default function WilsonsOnly({ pageName, setPage }) {
  const { setLeague } = useLeague()

  function handleSwitch() {
    setLeague(WMH_ID, WMH_NAME)
    setPage('home')
  }

  return (
    <div className='page'>
      <div className='page-title'>{pageName}</div>
      <div style={{ display: 'flex', justifyContent: 'center', marginTop: '3rem' }}>
        <div className='card' style={{ maxWidth: '480px', width: '100%', padding: '2.5rem', textAlign: 'center' }}>
          <div style={{ fontSize: '2.5rem', marginBottom: '1rem', lineHeight: 1 }}>🔒</div>
          <h3 style={{
            color: 'var(--text-primary)', marginBottom: '0.75rem',
            fontSize: '16px', fontWeight: 700,
          }}>
            Wilson's Moms House Only
          </h3>
          <p style={{
            color: 'var(--text-secondary)', fontSize: '13px',
            lineHeight: 1.7, marginBottom: '1.75rem',
          }}>
            This feature is generated by a pipeline specific to this league and is not
            available for external leagues.
          </p>
          <button
            onClick={handleSwitch}
            style={{
              padding: '9px 22px',
              background: '#3182ce', border: 'none', borderRadius: '8px',
              color: '#fff', fontWeight: 600, fontSize: '13px', cursor: 'pointer',
              transition: 'background 0.15s',
            }}
            onMouseEnter={e => { e.currentTarget.style.background = '#2b6cb0' }}
            onMouseLeave={e => { e.currentTarget.style.background = '#3182ce' }}
          >
            Switch to Wilson's Moms House
          </button>
        </div>
      </div>
    </div>
  )
}
